const { GoogleSpreadsheet } = require("google-spreadsheet");
const fs = require("fs");
require('dotenv').config()


function getGoogleSheet() {
    // Initialize the sheet - doc ID is the long id in the sheets URL

    const sheetId = process.env.SHEET_ID;
    const email = process.env.EMAIL;
    const key = process.env.KEY;

    const doc = new GoogleSpreadsheet(sheetId);

    try {
        ( async () => {
            try {
                await doc.useServiceAccountAuth({
                    // env var values are copied from service account credentials generated by google
                    // see "Authentication" section in docs for more info
                    client_email:  email,
                    private_key: key,
                });
                await doc.loadInfo()
                const peoples = doc.sheetsByTitle['People']; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
                const activities = doc.sheetsByTitle['Activity'];

                const peoplesRow = await peoples.getRows();
                const activitiesRow = await activities.getRows();

                const peopleMap = [];
                const activityMap = [];

                peoplesRow.forEach(it => {
                    const row = it['_rawData'];
                    const key = row[0];
                    const period = row[1];
                    const isOrganizer = row[2] === 'TRUE';
                    const thumbnail = row[3];
                    const name = row[4];
                    const part = row[5];
                    const introduce = row[6];
                    const review = row[7];
                    const github = row[8];
                    const linkedin = row[9];
                    const etc = row[10];
                    peopleMap.push({
                        id: key,
                        period: period,
                        isOrganizer: isOrganizer,
                        thumbnail: thumbnail,
                        name: name,
                        part: part,
                        introduce: introduce,
                        review: review,
                        github: github,
                        linkedin: linkedin,
                        etc: etc,
                    })
                })

                activitiesRow.forEach(it => {
                    const row = it['_rawData'];
                    const key = row[0];
                    const type = row[1];
                    const thumbnail = row[2];
                    const title = row[3];
                    const description = row[4];
                    const name = row[5];
                    const date = row[6];
                    const link = row[7];

                    activityMap.push({
                        id: key,
                        type: type,
                        thumbnail: thumbnail,
                        title: title,
                        description: description,
                        name: name,
                        date: date,
                        link: link,
                    })
                });


                const json = {
                    peoples: peopleMap,
                    activities: activityMap,
                }

                fs.writeFile('src/db/index.json', JSON.stringify(json), { flag: 'w+' }, function (err) {
                    if (err) return console.error(err);
                });

            } catch (e) {
                console.error(e);
            }
        })();
    } catch(e) {
        console.error(e)
    }

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication

}

getGoogleSheet();