compressionLevel: mixed

enableGlobalCache: false

npmScopes:
  sipe-team:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: "${NODE_ENV==='local' ? '' : NODE_AUTH_TOKEN}"


supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin

yarnPath: .yarn/releases/yarn-4.5.0.cjs
